# Generated by Django 5.2.17 on 2026-09-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DernierePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date_envoi', models.DateTimeField(auto_now=True)),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derniere_position', to='flotte.vehicule')),
            ],
        ),
    ]
