# Generated by Django 5.2.17 on 2026-09-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(max_length=100)),
                ('poids', models.DecimalField(decimal_places=2, help_text='en kg', max_digits=8)),
                ('hauteur', models.DecimalField(decimal_places=2, help_text='en m', max_digits=5)),
                ('largeur', models.DecimalField(decimal_places=2, help_text='en m', max_digits=5)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('EN_PANNE', 'En panne')], default='DISPONIBLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='comptes.responsable')),
            ],
        ),
    ]
