# Generated by Django 5.2.17 on 2026-09-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur', models.CharField(max_length=255)),
                ('nombre_vehicules_demandes', models.PositiveIntegerField()),
                ('date_chargement', models.DateField()),
                ('heure_chargement', models.TimeField()),
                ('point_depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('TRAITE', 'Traité'), ('ANNULEE', 'Annulée')], default='PREVU', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_chargement', to='comptes.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PREVU', max_length=20)),
                ('date_fin_prevue', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_terminee', models.DateTimeField(blank=True, null=True)),
                ('date_annulee', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='comptes.agent')),
                ('demande_chargement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='operations.demandechargement')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='flotte.vehicule')),
            ],
        ),
    ]
