# Generated by Django 5.2.17 on 2026-09-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_agent_categorie_permis_agent_numero_permis_and_more'),
        ('flotte', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='comptes.agent'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='flotte.vehicule'),
        ),
    ]
