# Generated by Django 5.2.17 on 2026-09-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_agent_categorie_permis_agent_numero_permis_and_more'),
        ('operations', '0002_alter_mission_agent_alter_mission_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_TERMINEE', 'Mission terminée')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.mission')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comptes.responsable')),
            ],
        ),
    ]
